### ISSUE TITLE
Something Wrong

### ISSUE THREAD

**Issue by WangWenhao0716** [yxgeee/MMT#7]
**MMT/examples/data**
├── dukemtmc
│   └── DukeMTMC-reID
├── market1501
│   └── Market-1501-v15.09.15
└── msmt17
    └── MSMT17_V1

should be:

**MMT/data**
├── dukemtmc
│   └── DukeMTMC-reID
├── market1501
│   └── Market-1501-v15.09.15
└── msmt17
    └── MSMT17_V1

**Comment by yxgeee** [comment]
Thank you for your reminder.
In your case, I suppose you have moved the `mmt_train.py` file from `MMT/examples/` to `MMT/`,
since the data directory is defined in [mmt_train.py](https://github.com/yxgeee/MMT/blob/master/examples/mmt_train.py#L272) depended on the absolute path of `mmt_train.py`.

Anyway, it could not be considered as an error as the user can define the data path by setting `--data-dir` when running.

**Comment by WangWenhao0716** [comment]
OK, I know. Thanks for your reply!
